name: Next.js CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Staging
        env:
          HOST_PASSWORD: ${{ secrets.HOST_PASSWORD }}
        run: |
          # Build and push Docker image
          docker build -t my-nextjs-app .
          docker push my-nextjs-app:latest
          
          # Deploy to staging server
          ssh user@staging-host 'docker pull my-nextjs-app:latest && docker stop my-nextjs-app && docker rm my-nextjs-app && docker run -d --name my-nextjs-app -p 3000:3000 my-nextjs-app:latest'
